version: '3'
services:
  postgres:
    container_name: spring-boot-postgres
    image: postgres:alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: